cafeLogProject/frontend

eslint.config.mjs, package-lock.json, package.json, src/App.tsx, src/pages/CafeInfo.tsx, src/pages/CafeSearch.tsx, src/pages/Home.tsx, src/pages/Login.tsx, src/pages/MyPage.tsx, src/pages/WriteReview.tsx, tsconfig.app.json, vite.config.ts
- 로그인, 메인(홈), 카페검색, 리뷰작성, 카페정보, 마이페이지 추가했습니다.
- 간단한 라우팅 설정을 했습니다.
- 전역경로를 사용하기 위해 tsconfig.app.json 파일에 관련 설정을 추가했습니다.
=> feat: 페이지 추가, 간단한 라우팅, 전역경로 설정

package-lock.json, package.json, src/app/auth/useAuthStore.ts, src/app/routers/ProtectedRoute.tsx, src/app/routers/appRouter.tsx, src/pages/Login.tsx, src/shared/ui/button/Button.tsx
- 홈, 카페 검색, 리뷰 작성, 카페 정보, 마이페이지에 Protected Route 적용
- 로그인 페이지는 public 접근 허용
- 인증되지 않은 경우 로그인 페이지로 리다이렉트
- 인증 상태 관리를 위한 Zustand 스토어 구현
- useAuthStore 훅을 통한 전역 인증 상태 관리
- localStorage에 인증 상태 저장
- 백엔드로 실제로 요청 후 isAuthentcated 플래그 설정
=> feat: Protected Route 및 인증 상태 관리 구현

package-lock.json, src/pages/CafeSearch.tsx, src/pages/styles/CafeSearch.module.scss, src/shared/api/cafe/cafeSearch.ts, src/shared/api/cafe/mockData.ts
- 카페 검색 API 호출 실패 시 개발 환경에서는 더미 데이터를 반환하도록 수정
- 검색 결과가 없거나 오류 발생 시 콘솔 로그 참조(임시)
- 로딩 상태와 에러 상태에 대한 스타일 추가
=> feat: 개발환경에서 네이버 API 호출 오류 시 더미 데이터 처리

src/shared/ui/bottomSheet/BottomSheet.module.scss
- 날짜 선택 시 달력 바텀시트가 너무 높이 올라오는 문제 수정
=> fix: DatePicker Bottomsheet 높이 수정

src/app/styles/abstracts/_variables.scss, src/entities/cafeListItem/CafeListItem.tsx, src/pages/WriteReview.module.scss, src/pages/WriteReview.tsx, src/shared/store/useReviewDraftStore.ts, src/shared/ui/tag/index.ts, src/shared/ui/tag/types/types.ts, src/shared/ui/tag/ui/Tag.module.scss, src/shared/ui/tag/ui/Tag.tsx
=> feat: 태그 컴포넌트

package-lock.json, package.json, src/app/routers/appRouter.tsx, src/pages/styles/CafeSearch.module.scss
- swiper와 zustand 패키지 간의 쉼표 누락 수정
- 기본 인덱스 라우트를 Home에서 RevivewList로 변경
- Sass color 모듈 추가
- darken() 함수를 color.adjust()로 변경
=> fix: 소소한 수정들

src/app/styles/abstracts/_mixins.scss, src/app/styles/abstracts/_variables.scss, src/app/styles/base/_base.scss, src/app/styles/base/_reset.scss, src/entities/review/ui/reviewContent/ReviewContent.module.scss, src/entities/review/ui/reviewerInfo/ReviewerInfo.module.scss, src/shared/ui/chips/Chips.module.scss
variable 추가 : 색상, text-styles
mixins 추가 : text-styles
컴포넌트 variable 적용
=> refactor: varaible, mixins

package-lock.json, package.json, src/app/styles/base/_reset.scss, src/app/styles/main.scss
- 전역 scss 포함 순서 변경
- 불필요한 라이브러리 종속성 제거
- _reset.scss font: inherit; 삭제
=> fix: 폰트 문제 해결

src/app/layout/footer/Footer.module.scss, src/app/layout/footer/Footer.tsx
- 네비게이션 바의 각 버튼 주변에 `div` 래퍼를 추가하여 클릭 가능한 영역을 확장
- 사용자가 버튼을 더 쉽게 클릭할 수 있게 되어 모바일 UX가 개선
- 라우팅 페이지에 따라 navbar 아이템들의 스타일 변경
=> fix: 네비게이션 바 버튼 상호작용 영역 개선

src/app/layout/mainLayout/MainLayout.module.scss
- 헤더영역과 페이지 영역 사이 공간 계산 삭제
- .withHeader 셀렉터 삭제
=> fix: 헤더영역 스타일 수정

src/app/routers/appRouter.tsx, src/app/styles/abstracts/_variables.scss, src/entities/profile/ui/filterBtn/FilterBtn.module.scss, src/entities/profile/ui/filterBtn/FilterBtn.tsx, src/entities/profile/ui/index.ts, src/entities/profile/ui/profileHeader/ProfileHeader.module.scss, src/entities/review/ui/reviewerInfo/ReviewerInfo.module.scss, src/pages/Main.tsx, src/pages/MyPage.tsx, src/widgets/reviewList/index.ts, src/widgets/reviewList/ui/ReviewList.module.scss, src/widgets/reviewList/ui/ReviewList.tsx
- reviewFilter 버튼 레이아웃 작성
- 기존 reviewList 페이지 Main 페이지로 이름 변경
- reviewList 위젯으로 생성
- reviewList 마진, 패딩 재조정
=> feature: review 버튼 레이아웃

package-lock.json
=> chore: package-lock.json 추가

src/pages/WriteReview.tsx, src/pages/styles/WriteReview.module.scss
- 리뷰작성 페이지에 작성 완료 버튼 추가
- MainLayout 스타일 변경에 따른 페이지 레이아웃 설정
- 태그 정보를 API 호출 및 msw로 분리
=> feat: 작성 완료 버튼

src/app/layout/mainLayout/MainLayout.tsx, src/app/routers/appRouter.tsx, src/features/search/ui/SearchBar.tsx, src/shared/assets/images/write_button.svg, src/shared/ui/floatingButton/FloatingButton.module.scss, src/shared/ui/floatingButton/FloatingButton.tsx
- MainLayout에 FloatingButton 컴포넌트 추가
- FloatingButton UI 컴포넌트 구현
- 우측 하단에 고정된 버튼 추가 (fixed position)
- MainLayout props에 showWriteButton 옵션 추가 (기본값: true)
- WriteReview 페이지에서는 FloatingButton 비활성화
- 검색바에서 히스토리 누적 방지를 위해 navigate 시 replace 옵션 추가
=> feat: 리뷰 작성을 위한 Floating Button 추가

src/shared/ui/floatingButton/FloatingButton.module.scss
- 뷰포트가 넓을 경우 리뷰작성 버튼 위치의 계산식 설정
=> fix: 뷰포트가 넓을 경우 리뷰작성 버튼 위치

src/features/search/ui/SearchBar.module.scss, src/pages/styles/CafeSearch.module.scss, src/shared/ui/input/Input.module.scss, src/widgets/datePicker/ui/DatePicker.module.scss, src/widgets/datePicker/ui/DatePicker.tsx
- 검색, 리뷰작성 페이지의 각 컴포넌트의 padding을 설정
=> fix: 컴포넌트별 padding 설정

src/features/search/ui/SearchBar.tsx, src/mocks/handlers/auth.ts, src/mocks/handlers/cafe.ts, src/mocks/handlers/index.ts, src/mocks/handlers/review.ts, src/pages/CafeSearch.tsx, src/pages/WriteReview.tsx, src/shared/api/cafe/cafeSearch.ts, src/shared/api/cafe/mapper/cafeMapper.ts, src/shared/api/cafe/mockData.ts, src/shared/api/cafe/types.ts, src/shared/api/hooks/useApi.ts, src/shared/api/reviews/types.ts, vite.config.ts
- useApi 커스텀 훅 추가
- API 호출을 위한 재사용 가능한 커스텀 훅 구현
- 로딩 상태, 에러 처리, 성공/실패 콜백 지원
- GET, POST 메서드 구현
- 리뷰 작성 기능
- 리뷰 작성 시 폼 유효성 검사 추가
- 작성 완료 후 이전 페이지 또는 홈으로 이동
- 카페 검색 기능
- MSW를 활용한 카페 검색 API 모킹
- 네이버 로컬 API 응답 형식에 맞춘 데이터 매핑 추가
- 검색 결과가 없을 경우 더미 데이터 반환(개발 환경)
- 기타 변경사항
- 태그 데이터 구조 개선 (content → description)
- 검색 파라미터 변경 (query → name)
- CORS 설정 및 프록시 설정 개선
- CafeSearch.tsx의 fetchCafes 함수에서 useApi를 사용하지 않아 수정이 필요합니다.
=> feat: useApi 훅 추가 및 리뷰 작성/카페 검색 기능 구현

src/pages/styles/WriteReview.module.scss, src/shared/api/base.ts
- 개발 모드의 API 기본 URL을 'https://localhost:5173'에서 빈 문자열('')로 변경
- visitDateLabel과 tagContainer 클래스를 부모 클래스 내부로 이동
=> fix: dev 모드 요청경로 수정, WriteReview css 수정

src/mocks/handlers/image.ts, src/mocks/handlers/index.ts, src/mocks/handlers/review.ts, src/mocks/storage/ImageStorage.ts, src/mocks/storage/ReviewStorage.ts, src/pages/CafeSearch.tsx, src/pages/WriteReview.tsx, src/shared/api/hooks/useApi.ts, src/shared/api/images/index.ts, src/shared/api/images/types.ts, src/shared/api/reviews/reviewApi.ts, src/shared/api/reviews/types.ts, src/shared/store/photoUploaderStore.ts, src/shared/store/usePhotoUploaderStore.ts, src/shared/store/useReviewDraftStore.ts, src/shared/ui/floatingButton/FloatingButton.tsx, src/widgets/photoUploader/lib/constants.ts, src/widgets/photoUploader/lib/imageProcessing.ts, src/widgets/photoUploader/types/index.ts, src/widgets/photoUploader/ui/PhotoUploader.tsx
- 이미지 업로드/조회/삭제를 위한 API 구현
- 이미지 처리 관련 유틸리티 함수 추가 (리사이징, 압축)
- 리뷰 생성 및 조회를 위한 API 구현
- IndexedDB를 활용한 msw 개발 테스트 핸들러 추가
- 이미지 업로드 시 자동 리사이징 및 압축 기능 추가
- Draft 이미지 로딩(Draft가 존재하고 서버에 이미지가 있을 경우 서버에 요청)
- 이미지 업로드 실패 시 에러 처리
- 이미지 업로드/로딩 상태 UI
=> feat: 이미지 업로드/리뷰 등록 API 및 MSW 구현

src/app/styles/base/_base.scss
스크롤바 적용
- height 적용안됨
- firefox 고려안함
=> feature: scrollbar

src/shared/api/reviews/reviewApi.ts
=> fix: 리뷰 등록 api trailing slash 제거

src/pages/styles/WriteReview.module.scss, src/shared/ui/bottomSheet/BottomSheet.module.scss
- 바텀시트, 오버레이, 작성완료 버튼 스타일을 수정하여 width > 600px 인 경우에도 위치를 잡도록 변경
- 임시방편으로 해당 페이지 레이아웃 스타일 재설계 필요
=> fix: 바텀시트, 오버레이, 작성완료 버튼 스타일 수정

src/constants/tags.ts, src/mocks/handlers/cafe.ts, src/pages/CafeSearch.tsx, src/pages/WriteReview.tsx, src/shared/api/cafe/cafe.ts, src/shared/api/cafe/cafeSearch.ts, src/shared/api/cafe/mapper/cafeMapper.ts, src/shared/api/cafe/mockData.ts, src/shared/api/cafe/types.ts, src/shared/api/reviews/types.ts, src/shared/store/useReviewDraftStore.ts
- 카페 검색 기능 개선
- MSW 핸들러에서 카페 검색 로직 수정
- 카페 카테고리 필터링 기능 추가 (카페 카테고리 포함된 항목만 표시)
- 리뷰 작성 플로우 개선
- 리뷰 작성 성공 시 응답 처리 추가
- 태그 관련 상수를 별도 파일로 분리 (src/constants/tags.ts)
- ReviewResponse 타입 확장 (태그 카테고리, 이미지 ID 등 추가)
- 카페 저장 기능 일부 추가
- 카페 존재 여부 확인 API 추가
- 신규 카페 저장 API 추가
- 리뷰 작성 전 카페 저장 로직 구현
- ICafeDescription 인터페이스 업데이트
- 위치 정보 형식 변경 (좌표 -> mapx, mapy)
- 더미 데이터 업데이트
- 리뷰 저장 API 응답 타입 정의 추가
=> feat: 카페 검색 및 리뷰 작성 기능 개선

package-lock.json, package.json, src/app/styles/main.scss, src/app/styles/vendors/_modal.scss, src/pages/MyPage.tsx, src/shared/ui/modal/Modal.tsx
react-modal 적용
Mypage 맨 아래에 예시 만들어 놓은 상태
=> feature: modal

src/app/layout/mainLayout/MainLayout.module.scss, src/entities/profile/ui/profileHeader/ProfileHeader.module.scss, src/entities/profile/ui/profileHeader/ProfileHeader.tsx, src/pages/MyPage.tsx
- Footer 떨림 현상 문제를 수정
- height: 100vh로 레이아웃 전체 높이를 뷰포트에 고정
- overflow: hidden으로 레이아웃 밖으로 넘치는 스크롤을 차단
- flex: 1을 통해 남은 공간을 모두 차지하도록 설정
- 내부 .mainContent에만 overflow-y: auto로 스크롤을 컨텐츠 영역으로 제한
- 프로필 flickering 문제를 수정
- position: sticky에서 position: fixed로 변경
- 좌우 중앙 정렬을 위한 transform: translateX(-50%) 적용
- 최대 너비 600px 제한
- 모든 전환에 transition: all 0.3s ease 적용
- 헤더 크기 변경 시 스크롤 위치 보정 로직
- 헤더가 축소될 때 발생하는 컨텐츠 점프 현상을 방지
- requestAnimationFrame을 사용해 다음 렌더링 프레임에서 스크롤 위치를 보정
=> fix: Footer 떨림효과, 프로필 flickering 수정

src/app/layout/mainLayout/MainLayout.module.scss, src/app/layout/mainLayout/MainLayout.tsx, src/app/routers/appRouter.tsx, src/entities/profile/ui/profileHeader/ProfileHeader.tsx, src/entities/review/ui/reviewItem/ReviewItem.tsx, src/pages/CafeInfo.tsx, src/pages/Main.tsx, src/pages/MyPage.tsx, src/shared/api/reviews/reviewApi.ts, src/shared/api/reviews/types.ts, src/shared/ui/chips/Chips.module.scss, src/shared/ui/photoSwiper/PhotoSwiper.module.scss, src/shared/ui/photoSwiper/PhotoSwiper.tsx, src/widgets/reviewList/ui/ReviewList.tsx
1. **프로필 정보 동적 로딩**
- 하드코딩된 프로필 정보를 API 호출을 통해 동적으로 가져오도록 수정
- 프로필 닉네임, 자기소개 정보 연동
2. **리뷰 목록 기능 개선**
- ReviewList 컴포넌트에 type 프로퍼티 추가 ('all'/'my')
- 전체 리뷰와 내 리뷰를 구분하여 표시
3. **리뷰 작성 기능**
- 카페 상세 페이지에서 리뷰 작성 페이지로의 네비게이션 구현
- 
4. **UI/UX 개선**
- 모바일 디바이스 환경에서 뷰포트의 높이가 다른 경우(주소창) 발생하는 UI문제(Footer가 가려짐) 수정
- PhotoSwiper 컴포넌트에 카페 이름 표시 기능 추가
- 장소 검색 페이지의 불필요한 완료 버튼 제거
- 이미지가 없는 경우에도 카페 이름 Chips가 표시되도록 개선
- Chips 컴포넌트 스타일 개선
- 고정 너비를 제거하고 컨텐츠에 맞게 조정되도록 변경
- 긴 카페 이름에 대한 텍스트 오버플로우 처리 추가(말줄임표 적용)
- API 로직을 별도로 분리할 경우 발생하는 문제
- 현재는 useCallback과 useEffect에 의존성을 추가하여 해결하고 있습니다.
- Data fetching 라이브러리(React Query, SWR)를 사용한 해결방법이 권장됩니다.
=> feat: 모바일 뷰포트 문제 해결, 마이페이지 관련 API 개선 및 적용

src/entities/profile/ui/profileHeader/ProfileHeader.module.scss, src/entities/review/ui/reviewItem/ReviewItem.tsx, src/pages/CafeSearch.tsx, src/pages/MyPage.tsx, src/pages/styles/CafeSearch.module.scss, src/pages/styles/Login.module.scss, src/shared/api/cafe/mapper/cafeMapper.ts, src/shared/ui/chips/Chips.tsx, src/shared/ui/photoSwiper/PhotoSwiper.tsx
- 프로필헤더 높이, 프로필 사진 크기, 로그인 페이지 스타일 수정
- 검색바를 sticky position으로 변경하여 스크롤 시에도 상단에 고정
- 카페 Chips 클릭 시 해당 카페 상세 페이지로 이동하는 네비게이션 기능 추가
- 카페 제목 sanitizer 개선
-HTML 엔티티(&, <, > 등) 디코딩 로직 추가
=> feat: UI/UX 개선 및 카페 Chips 네비게이션 기능 추가

src/pages/CafeInfo.tsx, src/shared/api/cafe/cafe.ts
- CafeInfo 컴포넌트의 API 호출 로직을 단순화
- 불필요한 useCallback과 useRef 의존성을 제거
- 카페 정보와 리뷰 데이터를 하나의 useEffect에서 순차적으로 가져오도록 수정
- useCafeApi의 getCafe 함수에 onSuccess, onError 콜백 옵션을 추가
- 이러한 패턴의 API 호출들을 같은 방식으로 리팩토링
=> refactor: 카페정보 페이지 API 호출 로직 개선

src/pages/MyPage.tsx
=> refactor: 사용하지 않는 계산식 주석처리

src/entities/profile/ui/profileHeader/ProfileHeader.module.scss, src/entities/review/ui/reviewItem/ReviewItem.tsx, src/pages/CafeInfo.tsx, src/pages/CafeSearch.tsx, src/pages/MyPage.tsx, src/pages/styles/CafeSearch.module.scss, src/pages/styles/Login.module.scss, src/shared/api/cafe/cafe.ts, src/shared/api/cafe/mapper/cafeMapper.ts, src/shared/ui/chips/Chips.tsx, src/shared/ui/fullScreenViewer/FullScreenViewer.module.scss, src/shared/ui/fullScreenViewer/FullScreenViewer.tsx, src/shared/ui/photoSwiper/PhotoSwiper.module.scss, src/shared/ui/photoSwiper/PhotoSwiper.tsx, src/widgets/photoUploader/lib/constants.ts
=> Release v0.0.2: 이미지 뷰어 추가, 페이지 기능/스타일 개선

src/entities/cafeListItem/CafeListItem.module.scss, src/features/writeReview/ui/TagSelector.module.scss, src/features/writeReview/ui/TagSelector.tsx, src/pages/WriteReview.tsx, src/pages/styles/WriteReview.module.scss, src/shared/ui/tag/ui/Tag.module.scss
- 텍스트 스타일 일관성 개선
- mixins.apply-text-style 적용하여 폰트 스타일 통일
- b1_bold, b2_bold, b2_regular 등 정의된 텍스트 스타일 사용
- 색상 변수 적용
-하드코딩된 색상값을 시맨틱 변수로 변경
- "인테리어" 레이블을 "매장"으로 변경
=> style: 리뷰 작성 페이지 스타일 수정

src/pages/WriteReview.tsx
- cafeId가 존재하지 않으면 홈("/")으로 이동
- 모달 state 변경 전 navigate로 url 변경되지 않는 문제 수정
=> fix: 모달 state 변경 전 navigate로 url 변경되지 않는 문제 수정

src/app/layout/footer/Footer.module.scss, src/app/layout/footer/Footer.tsx, src/app/layout/mainLayout/MainLayout.module.scss
- Footer position을 변경(fixed)하여 ios에서 드래그가 가능한 문제를 수정
=> fix: ios에서 footer의 드래그가 가능한 문제

src/app/layout/footer/Footer.module.scss, src/app/layout/header/Header.module.scss, src/app/layout/mainLayout/MainLayout.module.scss
- 헤더를 fixed 속성으로 고정
- ios에서 발생하는 메인레이아웃 오버스크롤 문제를 수정
=> fix: 헤더 고정 및 메인페이지 오버스크롤 방지

src/app/layout/footer/Footer.module.scss, src/app/layout/header/Header.module.scss
- Header와 Footer 컴포넌트에 스크롤 제어를 위한 CSS 속성 추가
- `touch-action: none`
- `pointer-events: none`
- 실제 상호작용이 필요한 영역에만 `pointer-events: auto` 적용
=> fix: Header, Footer 컴포넌트 스크롤 제어

src/entities/review/ui/reviewItem/ReviewItem.tsx, src/entities/review/ui/reviewMore/ReviewMore.tsx, src/entities/review/ui/reviewerInfo/ReviewerInfo.tsx, src/shared/api/reviews/reviewApi.ts, src/shared/api/user/types.ts, src/widgets/reviewList/ui/ReviewList.tsx
- 리뷰 삭제 API 연동
- 리뷰 작성자만 수정/삭제 버튼이 보이도록 권한 관리
- 리뷰 삭제 시 확인 모달 추가
- ReviewMore 컴포넌트에 리뷰 삭제 기능 추가
- ReviewItem에 currentUserId prop 추가하여 작성자 확인
- ReviewerInfo 컴포넌트에서 작성자 여부에 따라 더보기 버튼 표시 조건 추가
- 리뷰 삭제 시 사용자 확인을 위한 모달
=> feat: 리뷰 삭제 기능 구현

src/entities/profile/ui/photoEdit/PhotoEdit.tsx, src/pages/MyPageEdit.tsx, src/shared/api/user/useProfileImagesApi.ts, src/shared/store/useProfileStore.ts
=> feature: 이미지 조회 api

src/entities/review/ui/reviewerInfo/ReviewerInfo.tsx, src/shared/api/user/useProfileImagesApi.ts
- getProfileImage 항상 타임스탬프 설정(백엔드에서 개선 필요)
- ReviewerInfo 프로필 이미지 불러오기 API 사용
=> fix: getProfileImage 타임스탬프 설정, ReviewerInfo 프로필 이미지 API 사용

src/pages/MyPage.tsx
- 마이페이지에서 테스트용 버튼(Modal, Toast)을 삭제
=> refactor: 마이페이지 버튼 제

src/pages/WriteReview.tsx
- useBlocker에서 pushState 호출 최적화
=> fix: useBlocker에서 pushState 호출 최적화
